# Generated by Django 5.1.6 on 2025-06-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verzija1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('tip', models.CharField(max_length=50)),
                ('reg_broj', models.CharField(max_length=20)),
                ('godiste', models.IntegerField()),
                ('boja', models.CharField(max_length=20)),
                ('kilometri', models.IntegerField()),
                ('stanje', models.IntegerField()),
                ('servis', models.CharField(blank=True, max_length=50, null=True)),
                ('servis_datum', models.DateField(blank=True, null=True)),
                ('servis_kilometri', models.IntegerField(blank=True, null=True)),
                ('servis_cijena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servis_opis', models.TextField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verzija1.firma')),
            ],
        ),
    ]
