# Generated by Django 5.1.6 on 2025-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verzija1', '0002_vozilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmauser',
            name='ovlastenje',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
