# Generated by Django 5.1.6 on 2025-10-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verzija1', '0003_firmauser_ovlastenje'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozilo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
