# Generated by Django 5.1.6 on 2025-10-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verzija1', '0004_vozilo_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('datum_prijave', models.DateTimeField(auto_now_add=True)),
                ('datum_rijesenja', models.DateTimeField(blank=True, null=True)),
                ('cijena_popravka', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField()),
                ('vozilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verzija1.vozilo')),
            ],
        ),
    ]
