# Generated by Django 5.1.6 on 2025-10-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verzija1', '0005_kvar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvar',
            name='firma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='verzija1.firma'),
            preserve_default=False,
        ),
    ]
